#pragma once

// ----------------------------------------------------------------------------
// THIS HELPER CODE WAS GENERATED BY GEMINI
// ----------------------------------------------------------------------------

#include "GL/glew.h"

#include <functional>
#include <vector>

// ----------------------------------------------------------------------------
// Mesh
// ----------------------------------------------------------------------------

class Mesh
{
private:
  GLuint VAO = 0;
  GLuint VBO = 0;
  GLuint EBO = 0;
  GLsizei indexCount = 0;

public:
  Mesh();
  ~Mesh();

  Mesh(const Mesh& other) = delete;
  Mesh& operator=(const Mesh& other) = delete;

  Mesh(Mesh&& other);
  Mesh& operator=(Mesh&& other);

  // ====================================================================
  // THE REQUIRED FUNCTION: Setup and upload data to the GPU
  // ====================================================================
  void setup(const std::vector<GLfloat>& vertices,
             const std::vector<GLuint>& indices);

  void adjust(const std::function<void(void)>& f);

  // ====================================================================
  // THE DRAWING FUNCTION
  // ====================================================================
  void draw() const;
};

// ----------------------------------------------------------------------------
// createShaderProgram
// ----------------------------------------------------------------------------

/**
 * @brief Compiles vertex and fragment shaders and links them into a program.
 * * @param vertexShaderSource The source code string for the vertex shader.
 * @param fragmentShaderSource The source code string for the fragment shader.
 * @return GLuint The ID of the successfully compiled and linked shader program,
 * or 0 on failure.
 */
GLuint
createShaderProgram(const char* vertexShaderSource,
                    const char* fragmentShaderSource);

// ----------------------------------------------------------------------------