#pragma once

// ----------------------------------------------------------------------------
// THIS HELPER CODE WAS GENERATED BY GEMINI
// ----------------------------------------------------------------------------

#include "GL/glew.h"

#include <vector>

// ----------------------------------------------------------------------------
// Mesh
// ----------------------------------------------------------------------------

class Mesh
{
private:
  GLuint VAO;
  GLuint VBO;
  GLuint EBO;
  GLsizei indexCount;

public:
  Mesh();
  ~Mesh();

  // ====================================================================
  // THE REQUIRED FUNCTION: Setup and upload data to the GPU
  // ====================================================================
  void setup(const std::vector<GLfloat>& vertices,
             const std::vector<GLuint>& indices);

  // ====================================================================
  // THE DRAWING FUNCTION
  // ====================================================================
  void draw() const;
};

// ----------------------------------------------------------------------------
// createShaderProgram
// ----------------------------------------------------------------------------

/**
 * @brief Compiles vertex and fragment shaders and links them into a program.
 * * @param vertexShaderSource The source code string for the vertex shader.
 * @param fragmentShaderSource The source code string for the fragment shader.
 * @return GLuint The ID of the successfully compiled and linked shader program,
 * or 0 on failure.
 */
GLuint
createShaderProgram(const char* vertexShaderSource,
                    const char* fragmentShaderSource);

// ----------------------------------------------------------------------------