add_library(Samples_Draw3D_Dependencies INTERFACE)
target_link_libraries(Samples_Draw3D_Dependencies INTERFACE Chimia_Draw3D Samples_Utils)
target_compile_features(Samples_Draw3D_Dependencies INTERFACE cxx_std_17)

add_executable(Samples_Draw3D_ex1 ex1-triangles.cpp)
target_link_libraries(Samples_Draw3D_ex1 PRIVATE Samples_Draw3D_Dependencies)

add_executable(Samples_Draw3D_ex2 ex2-vertexColoredTriangles.cpp)
target_link_libraries(Samples_Draw3D_ex2 PRIVATE Samples_Draw3D_Dependencies)

add_executable(Samples_Draw3D_ex3 ex3-camera.cpp)
target_link_libraries(Samples_Draw3D_ex3 PRIVATE Samples_Draw3D_Dependencies)

add_executable(Samples_Draw3D_ex4 ex4-basicIllumination.cpp)
target_link_libraries(Samples_Draw3D_ex4 PRIVATE Samples_Draw3D_Dependencies)

add_executable(Samples_Draw3D_ex5 ex5-vertexColoredRenderer.cpp)
target_link_libraries(Samples_Draw3D_ex5 PRIVATE Samples_Draw3D_Dependencies)