#pragma once

#define CHIMIA_DRAW3D_NAMESPACE_NAME Chimia::Draw3D

#define BEGIN_CHIMIA_DRAW3D_NAMESPACE namespace CHIMIA_DRAW3D_NAMESPACE_NAME {
#define END_CHIMIA_DRAW3D_NAMESPACE }

#define USING_CHIMIA_DRAW3D_NAMESPACE using namespace CHIMIA_DRAW3D_NAMESPACE_NAME;
